name: GitHub Breakout

on:
  schedule:
    # Runs every day at midnight.
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-svg:
    name: Update breakout SVG
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cyprieng/github-breakout@main
        with:
          github_username: joseorteha
          github_token: ${{ secrets.GITHUB_TOKEN }}
